preload = ~/.config/hypr/assets/wallpaper.png

# 设置壁纸到特定的显示器
# wallpaper = HDMI-A-1,~/Pictures/Wallpapers/another_wallpaper.png

# 或设置所有显示器使用同一张壁纸
wallpaper = ,~/.config/hypr/assets/wallpaper.png

# 缩放模式 (可选: fill, stretch, center, contain, orig)
# 默认是 fill
# common_render_params = keep_aspect_ratio, 1 # 保持图片纵横比

# 当壁纸图片发生变化时，是否自动重新加载
ipc = 1
