general {
    lock_cmd = pidof hyprlock || hyprlock       # 避免同时开启多个 hyprlock 实例
    before_sleep_cmd = loginctl lock-session    # 休眠前先行锁定（非常重要！）
    after_sleep_cmd = hyprctl dispatch dpms on  # 唤醒后点亮屏幕
}

listener {
    timeout = 300                                # 5分钟不操作
    on-timeout = loginctl lock-session           # 触发锁屏
}

listener {
    timeout = 330                                # 5.5分钟不操作
    on-timeout = hyprctl dispatch dpms off       # 关闭显示器省电
    on-resume = hyprctl dispatch dpms on         # 鼠标动了就点亮
}